services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: rag-search-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rag_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rag_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  rag-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-search-api
    ports:
      - "8010:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__RagDb: Host=postgres;Port=5432;Database=rag_db;Username=postgres;Password=postgres
      Embedding__BaseUrl: http://embedding:8034/v1
      Embedding__ApiKey: not-used
      Embedding__ModelName: nomic-ai/nomic-embed-text-v2-moe
      Embedding__Dimension: 768
      LLM__BaseUrl: http://llm:8033/v1
      LLM__ApiKey: not-used
      LLM__ModelName: llama3
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads

  embedding:
    image: ghcr.io/ggml-org/llama.cpp:server
    container_name: rag-embedding
    privileged: true
    restart: always
    volumes:
      - D:\\.lmstudio\\models\\nomic-ai\\nomic-embed-text-v2-moe-GGUF:/models
    ports:
      - "8034:8034"
    command: >
      -m "/models/nomic-embed-text-v2-moe.Q8_0.gguf"
      --jinja
      --flash-attn 1
      --fit on
      --port 8034
      --no-mmap
      --offline
      --embeddings

  llm:
    image: ghcr.io/ggml-org/llama.cpp:server
    container_name: rag-llm
    privileged: true
    restart: always
    volumes:
      - D:\\.lmstudio\\models\\meta-llama\\llama3\\llama3-8b-q8_0.gguf:/models
    ports:
      - "8033:8033"
    command: >
      -m "/models/llama3-8b-q8_0.gguf"
      --jinja
      --flash-attn 1
      --ctx-size 4096
      --port 8033
      -c 4096

volumes:
  postgres_data: